Repository CS2103JAN2018-T09-B3/main, pull requests merged in 2018-04, with the labels that each got.

#149 Close issue on github
  src/main/java/seedu/progresschecker/logic/CommandFormatListUtil.java
  src/main/java/seedu/progresschecker/logic/commands/CloseIssueCommand.java
  src/main/java/seedu/progresschecker/logic/parser/CloseIssueCommandParser.java
  src/main/java/seedu/progresschecker/logic/parser/ProgressCheckerParser.java
  src/main/java/seedu/progresschecker/model/Model.java
  src/main/java/seedu/progresschecker/model/ModelManager.java
  src/main/java/seedu/progresschecker/model/ProgressChecker.java
  src/test/java/seedu/progresschecker/logic/commands/AddCommandTest.java
Labels: type.task

#153 Read exercises from data/progresschecker.xml if exist, otherwise read from sample data
  docs/UserGuide.adoc
  docs/team/johndoe.adoc
  src/main/java/seedu/progresschecker/commons/events/ui/PageLoadChangedEvent.java
  src/main/java/seedu/progresschecker/logic/Logic.java
  src/main/java/seedu/progresschecker/logic/LogicManager.java
  src/main/java/seedu/progresschecker/model/Model.java
  src/main/java/seedu/progresschecker/model/ModelManager.java
  src/main/java/seedu/progresschecker/model/ProgressChecker.java
  src/main/java/seedu/progresschecker/model/ReadOnlyProgressChecker.java
  src/main/java/seedu/progresschecker/model/exercise/Exercise.java
  src/main/java/seedu/progresschecker/model/exercise/ModelAnswer.java
  src/main/java/seedu/progresschecker/model/exercise/Question.java
  src/main/java/seedu/progresschecker/model/exercise/QuestionIndex.java
  src/main/java/seedu/progresschecker/model/exercise/QuestionType.java
  src/main/java/seedu/progresschecker/model/exercise/StudentAnswer.java
  src/main/java/seedu/progresschecker/model/exercise/UniqueExerciseList.java
  src/main/java/seedu/progresschecker/model/exercise/exceptions/DuplicateExerciseException.java
  src/main/java/seedu/progresschecker/model/util/SampleDataUtil.java
  src/main/java/seedu/progresschecker/storage/XmlAdaptedExercise.java
  src/main/java/seedu/progresschecker/storage/XmlSerializableProgressChecker.java
  src/main/java/seedu/progresschecker/ui/ExerciseCard.java
  src/main/java/seedu/progresschecker/ui/ExerciseListPanel.java
  src/main/java/seedu/progresschecker/ui/ExercisesPanel.java
  src/main/java/seedu/progresschecker/ui/MainWindow.java
  src/main/resources/view/ExerciseListCard.fxml
  src/main/resources/view/ExerciseListPanel.fxml
  src/main/resources/view/ExercisesPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/progresschecker/logic/commands/AddCommandTest.java
  src/test/java/seedu/progresschecker/model/ProgressCheckerTest.java
Labels: type.enhancement

#154 update upload photo command
  src/main/java/seedu/progresschecker/commons/util/FileUtil.java
  src/main/java/seedu/progresschecker/logic/commands/UploadCommand.java
  src/main/java/seedu/progresschecker/logic/parser/UploadCommandParser.java
  src/main/java/seedu/progresschecker/model/Model.java
  src/main/java/seedu/progresschecker/model/ModelManager.java
  src/main/java/seedu/progresschecker/model/ProgressChecker.java
  src/main/java/seedu/progresschecker/model/person/Person.java
  src/main/java/seedu/progresschecker/model/photo/PhotoPath.java
  src/main/java/seedu/progresschecker/model/photo/UniquePhotoList.java
  src/main/java/seedu/progresschecker/model/photo/exceptions/DuplicatePhotoException.java
  src/main/java/seedu/progresschecker/model/photo/exceptions/PhotoNotFoundException.java
  src/main/java/seedu/progresschecker/ui/PersonCard.java
  src/test/java/seedu/progresschecker/logic/commands/AddCommandTest.java
  src/test/java/seedu/progresschecker/logic/commands/UploadCommandTest.java
Labels: type.bug fix

#155 Made minor updates for exceptions
  src/main/java/seedu/progresschecker/model/Model.java
  src/main/java/seedu/progresschecker/model/ModelManager.java
  src/main/java/seedu/progresschecker/model/ProgressChecker.java
Labels: type.bug fix

#159 Update UserGuide
  docs/UserGuide.adoc
Labels: help wanted, type.documentation

#158 Updated user guide with the latest commands
  docs/UserGuide.adoc
Labels: type.documentation

#160 Task management 02
  src/main/java/seedu/progresschecker/logic/apisetup/ConnectTasksApi.java
  src/main/java/seedu/progresschecker/logic/commands/AddDefaultTasksCommand.java
  src/main/java/seedu/progresschecker/logic/commands/CompleteTaskCommand.java
  src/main/java/seedu/progresschecker/logic/commands/ResetTaskCommand.java
  src/main/java/seedu/progresschecker/logic/commands/ViewTaskListCommand.java
  src/main/java/seedu/progresschecker/logic/parser/CompleteTaskCommandParser.java
  src/main/java/seedu/progresschecker/logic/parser/ParserUtil.java
  src/main/java/seedu/progresschecker/logic/parser/ProgressCheckerParser.java
  src/main/java/seedu/progresschecker/logic/parser/ResetTaskCommandParser.java
  src/main/java/seedu/progresschecker/logic/parser/ViewTaskListCommandParser.java
  src/main/java/seedu/progresschecker/model/person/GithubUsername.java
  src/main/java/seedu/progresschecker/model/person/Major.java
  src/main/java/seedu/progresschecker/model/person/Person.java
  src/main/java/seedu/progresschecker/model/person/Year.java
  src/main/java/seedu/progresschecker/model/task/MyTask.java
  src/main/java/seedu/progresschecker/model/task/MyTaskList.java
  src/main/java/seedu/progresschecker/ui/BrowserPanel.java
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/defaultTasks.txt
  src/main/resources/view/sampleTasklist.html
  src/test/java/seedu/progresschecker/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/progresschecker/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/progresschecker/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/progresschecker/logic/parser/ParserUtilTest.java
  src/test/java/seedu/progresschecker/model/person/GithubUsernameTest.java
  src/test/java/seedu/progresschecker/model/person/MajorTest.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: type.enhancement

#170 Add collated folder and files
  collated/functional/EdwardKSG.md
  collated/functional/Livian1107.md
  collated/functional/adityaa1998.md
  collated/functional/iNekox3.md
  collated/test/EdwardKSG.md
  collated/test/Livian1107.md
Labels: type.documentation

#174 Add feature to answer an exercise based on index and have results be saved down
  docs/UserGuide.adoc
  src/main/java/seedu/progresschecker/commons/core/Messages.java
  src/main/java/seedu/progresschecker/logic/commands/AnswerCommand.java
  src/main/java/seedu/progresschecker/logic/parser/AnswerCommandParser.java
  src/main/java/seedu/progresschecker/logic/parser/ParserUtil.java
  src/main/java/seedu/progresschecker/logic/parser/ProgressCheckerParser.java
  src/main/java/seedu/progresschecker/model/Model.java
  src/main/java/seedu/progresschecker/model/ModelManager.java
  src/main/java/seedu/progresschecker/model/ProgressChecker.java
  src/main/java/seedu/progresschecker/model/exercise/QuestionIndex.java
  src/main/java/seedu/progresschecker/model/exercise/UniqueExerciseList.java
  src/main/java/seedu/progresschecker/model/exercise/exceptions/ExerciseNotFoundException.java
  src/main/java/seedu/progresschecker/model/util/SampleDataUtil.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DayTheme.css
  src/main/resources/view/ExerciseListCard.fxml
  src/main/resources/view/ExerciseListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/progresschecker/logic/commands/AddCommandTest.java
Labels: type.documentation, type.enhancement

#175 Implemented github login command
  src/main/java/seedu/progresschecker/logic/CommandFormatListUtil.java
  src/main/java/seedu/progresschecker/logic/commands/GitLoginCommand.java
  src/main/java/seedu/progresschecker/logic/parser/CliSyntax.java
  src/main/java/seedu/progresschecker/logic/parser/GitLoginCommandParser.java
  src/main/java/seedu/progresschecker/logic/parser/ParserUtil.java
  src/main/java/seedu/progresschecker/logic/parser/ProgressCheckerParser.java
  src/main/java/seedu/progresschecker/model/Model.java
  src/main/java/seedu/progresschecker/model/ModelManager.java
  src/main/java/seedu/progresschecker/model/ProgressChecker.java
  src/main/java/seedu/progresschecker/model/credentials/GitDetails.java
  src/main/java/seedu/progresschecker/model/credentials/Passcode.java
  src/main/java/seedu/progresschecker/model/credentials/Repository.java
  src/main/java/seedu/progresschecker/model/credentials/Username.java
  src/main/java/seedu/progresschecker/model/issues/GitIssueList.java
  src/test/java/seedu/progresschecker/logic/commands/AddCommandTest.java
Labels: type.task

#176 Update userguide with the latest command
  docs/UserGuide.adoc
Labels: type.documentation

#199 Modify view command to switch view between tabs
  docs/UserGuide.adoc
  src/main/java/seedu/progresschecker/commons/events/ui/PageLoadChangedEvent.java
  src/main/java/seedu/progresschecker/commons/events/ui/TabLoadChangedEvent.java
  src/main/java/seedu/progresschecker/commons/util/StringUtil.java
  src/main/java/seedu/progresschecker/logic/commands/ViewCommand.java
  src/main/java/seedu/progresschecker/logic/parser/ParserUtil.java
  src/main/java/seedu/progresschecker/logic/parser/ViewCommandParser.java
  src/main/java/seedu/progresschecker/ui/BrowserPanel.java
  src/main/java/seedu/progresschecker/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/progresschecker/logic/commands/ViewCommandTest.java
  src/test/java/seedu/progresschecker/logic/parser/ProgressCheckerParserTest.java
  src/test/java/seedu/progresschecker/testutil/TypicalTabTypes.java
  src/test/java/seedu/progresschecker/ui/BrowserPanelTest.java
  src/test/java/systemtests/ProgressCheckerSystemTest.java
Labels: type.documentation, type.enhancement

#203 Update Documentation
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/SDforUploadPhoto.png
Labels: type.documentation

#209 Documentation after Feedback
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/download1.png
  docs/images/download2.png
  docs/images/download3.png
Labels: type.documentation

#216 Add project portfolio
  docs/DeveloperGuide.adoc
  docs/team/yeeru.adoc
Labels: type.documentation

#220 Added a project portfolio
  docs/UserGuide.adoc
  docs/team/Adityaa1998.adoc
  docs/team/johndoe.adoc
Labels: type.documentation

#210 Added a tab for displaying the issues
  src/main/java/seedu/progresschecker/logic/CommandFormatListUtil.java
  src/main/java/seedu/progresschecker/logic/Logic.java
  src/main/java/seedu/progresschecker/logic/LogicManager.java
  src/main/java/seedu/progresschecker/logic/commands/CreateIssueCommand.java
  src/main/java/seedu/progresschecker/logic/commands/ViewCommand.java
  src/main/java/seedu/progresschecker/logic/parser/CreateIssueParser.java
  src/main/java/seedu/progresschecker/logic/parser/ParserUtil.java
  src/main/java/seedu/progresschecker/logic/parser/ProgressCheckerParser.java
  src/main/java/seedu/progresschecker/model/Model.java
  src/main/java/seedu/progresschecker/model/ModelManager.java
  src/main/java/seedu/progresschecker/model/ProgressChecker.java
  src/main/java/seedu/progresschecker/model/ReadOnlyProgressChecker.java
  src/main/java/seedu/progresschecker/model/issues/GitIssueList.java
  src/main/java/seedu/progresschecker/model/issues/Milestone.java
  src/main/java/seedu/progresschecker/model/issues/MilestoneMap.java
  src/main/java/seedu/progresschecker/model/issues/Title.java
  src/main/java/seedu/progresschecker/storage/XmlAdaptedAssignee.java
  src/main/java/seedu/progresschecker/storage/XmlAdaptedIssue.java
  src/main/java/seedu/progresschecker/storage/XmlAdaptedLabel.java
  src/main/java/seedu/progresschecker/storage/XmlProgressCheckerStorage.java
  src/main/java/seedu/progresschecker/storage/XmlSerializableProgressChecker.java
  src/main/java/seedu/progresschecker/ui/IssueCard.java
  src/main/java/seedu/progresschecker/ui/IssueListPanel.java
  src/main/java/seedu/progresschecker/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DayTheme.css
  src/main/resources/view/IssueListCard.fxml
  src/main/resources/view/IssueListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/progresschecker/logic/commands/AddCommandTest.java
  src/test/java/seedu/progresschecker/model/ProgressCheckerTest.java
Labels: type.story, type.task

#212 Add viewing of exercises in weeks and implement revelation of suggested answer
  docs/UserGuide.adoc
  src/main/java/seedu/progresschecker/commons/core/Messages.java
  src/main/java/seedu/progresschecker/commons/util/StringUtil.java
  src/main/java/seedu/progresschecker/logic/commands/AnswerCommand.java
  src/main/java/seedu/progresschecker/logic/commands/ViewCommand.java
  src/main/java/seedu/progresschecker/logic/parser/ParserUtil.java
  src/main/java/seedu/progresschecker/logic/parser/ViewCommandParser.java
  src/main/java/seedu/progresschecker/model/Model.java
  src/main/java/seedu/progresschecker/model/ModelManager.java
  src/main/java/seedu/progresschecker/model/exercise/QuestionIndex.java
  src/main/java/seedu/progresschecker/model/exercise/exceptions/DuplicateExerciseException.java
  src/main/java/seedu/progresschecker/model/util/SampleDataUtil.java
  src/main/java/seedu/progresschecker/ui/ExerciseCard.java
  src/main/java/seedu/progresschecker/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DayTheme.css
  src/main/resources/view/ExerciseListCard.fxml
  src/test/java/seedu/progresschecker/logic/commands/ViewCommandTest.java
  src/test/java/seedu/progresschecker/logic/parser/ProgressCheckerParserTest.java
  src/test/java/seedu/progresschecker/testutil/ExerciseBuilder.java
  src/test/java/seedu/progresschecker/ui/testutil/GuiTestAssert.java
Labels: type.enhancement

#213 Task management finalize
  src/main/java/seedu/progresschecker/commons/events/ui/LoadUrlEvent.java
  src/main/java/seedu/progresschecker/logic/commands/AddDefaultTasksCommand.java
  src/main/java/seedu/progresschecker/logic/commands/CompleteTaskCommand.java
  src/main/java/seedu/progresschecker/logic/commands/GoToTaskUrlCommand.java
  src/main/java/seedu/progresschecker/logic/commands/ResetTaskCommand.java
  src/main/java/seedu/progresschecker/logic/commands/ViewTaskListCommand.java
  src/main/java/seedu/progresschecker/logic/parser/CompleteTaskCommandParser.java
  src/main/java/seedu/progresschecker/logic/parser/DeleteCommandParser.java
  src/main/java/seedu/progresschecker/logic/parser/GoToTaskUrlCommandParser.java
  src/main/java/seedu/progresschecker/logic/parser/ParserUtil.java
  src/main/java/seedu/progresschecker/logic/parser/ProgressCheckerParser.java
  src/main/java/seedu/progresschecker/logic/parser/ResetTaskCommandParser.java
  src/main/java/seedu/progresschecker/logic/parser/ViewTaskListCommandParser.java
  src/main/java/seedu/progresschecker/model/task/TaskListUtil.java
  src/main/java/seedu/progresschecker/model/task/TaskUtil.java
  src/main/java/seedu/progresschecker/ui/BrowserPanel.java
  src/main/resources/defaultTasks.txt
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/sampleTasklist.html
  src/test/java/seedu/progresschecker/logic/parser/DeleteCommandParserTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
Labels: UI enhancement, type.enhancement, type.story

#218 add a Profile panel
  docs/UserGuide.adoc
  src/main/java/seedu/progresschecker/ui/MainWindow.java
  src/main/java/seedu/progresschecker/ui/PersonCard.java
  src/main/java/seedu/progresschecker/ui/ProfilePanel.java
  src/main/resources/images/github.png
  src/main/resources/images/profile_background.jpg
  src/main/resources/images/profile_background.png
  src/main/resources/images/profile_background_dark.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ProfilePanel.fxml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/progresschecker/ui/testutil/GuiTestAssert.java
Labels: UI enhancement

#230 Solved the wrong issue id problem
  src/main/java/seedu/progresschecker/model/issues/GitIssueList.java
  src/main/java/seedu/progresschecker/model/issues/Issue.java
  src/main/java/seedu/progresschecker/ui/IssueCard.java
  src/main/java/seedu/progresschecker/ui/IssueListPanel.java
Labels: type.bug fix

#223 add Theme command to change the theme
  docs/UserGuide.adoc
  src/main/java/seedu/progresschecker/commons/events/ui/ChangeThemeEvent.java
  src/main/java/seedu/progresschecker/logic/CommandFormatListUtil.java
  src/main/java/seedu/progresschecker/logic/commands/ThemeCommand.java
  src/main/java/seedu/progresschecker/logic/parser/ParserUtil.java
  src/main/java/seedu/progresschecker/logic/parser/ProgressCheckerParser.java
  src/main/java/seedu/progresschecker/logic/parser/ThemeCommandParser.java
  src/main/java/seedu/progresschecker/ui/MainWindow.java
  src/test/java/seedu/progresschecker/logic/commands/ThemeCommandTest.java
  src/test/java/seedu/progresschecker/testutil/TypicalThemes.java
Labels: type.enhancement

#228 Porfolio
  docs/UserGuide.adoc
  docs/team/liwen.adoc
Labels: type.documentation

#234 Portfolio eddie
  docs/UserGuide.adoc
  docs/team/EdwardKSG.adoc
Labels: type.documentation

#237 Collate v1.5rc
  collated/functional/EdwardKSG.md
  collated/functional/Livian1107.md
  collated/functional/adityaa1998.md
  collated/functional/iNekox3.md
  collated/test/Livian1107.md
  collated/test/iNekox3.md
  collated/unused/EdwardKSG-unused.md
  docs/team/EdwardKSG.adoc
  unused/remotePostgresConnection.java
  unused/schema.sql
Labels: type.documentation

#239 Add week2 tasks
  src/main/resources/defaultTasks.txt
Labels: type.task

#241 Task management minorupdate
  src/main/java/seedu/progresschecker/logic/commands/ViewTaskListCommand.java
Labels: type.task

#243 Change color scheme for both light and dark themes
  docs/team/yeeru.adoc
  src/main/java/seedu/progresschecker/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DayTheme.css
  src/main/resources/view/IssueListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ProfilePanel.fxml
  src/main/resources/view/TaskListCard.fxml
  src/test/java/systemtests/HelpCommandSystemTest.java
Labels: UI enhancement

#249 Code quality and minor functional improvements
  src/main/java/seedu/progresschecker/logic/CommandFormatListUtil.java
  src/main/java/seedu/progresschecker/logic/LogicManager.java
  src/main/java/seedu/progresschecker/logic/commands/CompleteTaskCommand.java
  src/main/java/seedu/progresschecker/logic/commands/GoToTaskUrlCommand.java
  src/main/java/seedu/progresschecker/logic/commands/ResetTaskCommand.java
  src/main/java/seedu/progresschecker/logic/commands/TaskCommandUtil.java
  src/main/java/seedu/progresschecker/logic/commands/ViewTaskListCommand.java
  tokens/StoredCredential
Labels: type.minor update

#261 Docs v1.5.1
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/HighLevelSDforViewTaskListCommand.png
  docs/images/LogicClassDiagram.png
  docs/images/SDforAddDefaultTaskList.png
  docs/images/SDforViewTaskListCommand.png
  docs/team/EdwardKSG.adoc
  token/StoredCredential
  tokens/StoredCredential
Labels: type.documentation

#264 Add tests for view and answer commands
  src/main/java/seedu/progresschecker/logic/parser/ParserUtil.java
  src/test/java/seedu/progresschecker/logic/commands/AnswerCommandTest.java
  src/test/java/seedu/progresschecker/logic/parser/AnswerCommandParserTest.java
  src/test/java/seedu/progresschecker/logic/parser/ViewCommandParserTest.java
Labels: test-cases

#265 Add manual testing info for view and answer command in DeveloperGuide
  docs/DeveloperGuide.adoc
Labels: type.documentation

#255 Update UI and test
  src/main/java/seedu/progresschecker/commons/util/FileUtil.java
  src/main/java/seedu/progresschecker/model/photo/PhotoPath.java
  src/main/java/seedu/progresschecker/ui/BrowserPanel.java
  src/main/java/seedu/progresschecker/ui/MainWindow.java
  src/main/java/seedu/progresschecker/ui/ProfilePanel.java
  src/main/resources/images/email.png
  src/main/resources/images/github.png
  src/main/resources/images/major.png
  src/main/resources/images/name.png
  src/main/resources/images/phone.png
  src/main/resources/images/profile_background0008.png
  src/main/resources/images/year.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/DayTheme.css
  src/main/resources/view/IssueListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/ProfilePanel.fxml
  src/main/resources/view/default.html
  src/test/java/guitests/guihandles/PersonListPanelHandle.java
  src/test/java/guitests/guihandles/ProfilePanelHandle.java
  src/test/java/seedu/progresschecker/commons/util/FileUtilTest.java
  src/test/java/seedu/progresschecker/model/photo/PhotoPathTest.java
  src/test/java/seedu/progresschecker/ui/BrowserPanelTest.java
  src/test/java/seedu/progresschecker/ui/ProfilePanelTest.java
  src/test/java/seedu/progresschecker/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/ClearCommandSystemTest.java
  src/test/java/systemtests/DeleteCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
  src/test/java/systemtests/ProgressCheckerSystemTest.java
  src/test/java/systemtests/SelectCommandSystemTest.java
Labels: type.bug fix
