Repository CS2103JAN2018-T09-B3/main, pull requests merged in 2018-03, with the labels that each got.

#20 refactor and add classes under "Person", resolve conflict files
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Major.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Year.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/XmlAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlAddressBookStorageTest/invalidAndValidPersonAddressBook.xml
  src/test/data/XmlAddressBookStorageTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/invalidPersonAddressBook.xml
  src/test/data/XmlSerializableAddressBookTest/typicalPersonsAddressBook.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/tempAddressBook.xml
  src/test/data/XmlUtilTest/validAddressBook.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/java/guitests/guihandles/PersonCardHandle.java
  src/test/java/seedu/address/commons/util/XmlUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/MajorTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/ui/testutil/GuiTestAssert.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: enhancement

#27 Dynamic search
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: enhancement

#26 Sort Command
  docs/UserGuide.adoc
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/SortCommandTest.java
Labels: enhancement

#25 Add command to display a specified week's LOs in BrowserPanel UI
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/PageLoadChangedEvent.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/ui/BrowserPanelTest.java
  src/test/java/systemtests/AddressBookSystemTest.java
Labels: enhancement

#43 update a use case about uploading profile picture
  docs/DeveloperGuide.adoc
Labels: Documentation Update

#66 Add Feature Contribution To Developer Guide
  docs/DeveloperGuide.adoc
Labels: Documentation Update

#70 Update liwen's features in developer guide
  docs/DeveloperGuide.adoc
Labels: Documentation Update

#68 add eddie's feature contribution to developer guide
  docs/DeveloperGuide.adoc
Labels: Documentation Update

#76 Update and correct User Stories and Use Cases in DeveloperGuide
  docs/DeveloperGuide.adoc
Labels: documentation

#103 Ui improvement
  src/main/java/seedu/progresschecker/MainApp.java
  src/main/java/seedu/progresschecker/ui/PersonCard.java
  src/main/resources/images/profile_photo.jpg
  src/main/resources/images/progress_checker.png
  src/main/resources/images/progress_checker_32.png
  src/main/resources/view/PersonListCard.fxml
Labels: minor update

#102 Display sample exercises in ExercisesPanel
  src/main/java/seedu/progresschecker/ui/ExercisesPanel.java
  src/main/resources/view/ExercisesPanel.fxml
Labels: minor update

#107 Update DG
  docs/DeveloperGuide.adoc
Labels: documentation

#108 Auto complete command implemented
  src/main/java/seedu/progresschecker/logic/CommandFormatListUtil.java
  src/main/java/seedu/progresschecker/logic/commands/AddCommand.java
  src/main/java/seedu/progresschecker/logic/commands/DeleteCommand.java
  src/main/java/seedu/progresschecker/logic/commands/EditCommand.java
  src/main/java/seedu/progresschecker/logic/commands/FindCommand.java
  src/main/java/seedu/progresschecker/logic/commands/SelectCommand.java
  src/main/java/seedu/progresschecker/logic/commands/SortCommand.java
  src/main/java/seedu/progresschecker/logic/commands/ViewCommand.java
  src/main/java/seedu/progresschecker/logic/parser/ProgressCheckerParser.java
  src/main/java/seedu/progresschecker/ui/CommandBox.java
  src/test/java/guitests/guihandles/CommandBoxHandle.java
  src/test/java/seedu/progresschecker/ui/CommandBoxTest.java
Labels: enhancement

#109 Added uml image
  docs/DeveloperGuide.adoc
  docs/images/FindCommandUMLDiagram.png
Labels: bug fix, documentation

#110 Add answering exercises implementation in DeveloperGuide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/SDforAnswerExercise.png
  docs/images/SDforExercisesEventHandling.png
Labels: documentation

#111 Docs v1.2
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.documentation

#114 UI minor enhacement
  src/main/resources/view/PersonListCard.fxml
Labels: type.bug fix

#117 update user guide
  docs/UserGuide.adoc
Labels: type.documentation

#100 Task management v1.2
  .gitignore
  build.gradle
  client_id.json
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/seedu/progresschecker/logic/apisetup/ConnectTasksApi.java
  src/main/java/seedu/progresschecker/logic/commands/AddDefaultTasksCommand.java
  src/main/java/seedu/progresschecker/logic/parser/ProgressCheckerParser.java
  src/main/java/seedu/progresschecker/model/person/Person.java
  src/main/java/seedu/progresschecker/model/task/MyTaskList.java
Labels: type.enhancement

#122 sequence diagram for adding default tasks
  docs/DeveloperGuide.adoc
  docs/images/SDforAddDefaultTaskList.png
Labels: type.documentation

#124 Add prefaces in main sections of User and Developer Guides
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.documentation

#123 Developer Guide Draft
  docs/DeveloperGuide.adoc
  docs/images/setup1.png
  docs/images/setup2.png
  docs/images/setup3.png
  docs/images/setup5.png
Labels: type.documentation

#121 Add new field: github username
  src/main/java/seedu/progresschecker/logic/commands/AddCommand.java
  src/main/java/seedu/progresschecker/logic/commands/EditCommand.java
  src/main/java/seedu/progresschecker/logic/parser/AddCommandParser.java
  src/main/java/seedu/progresschecker/logic/parser/CliSyntax.java
  src/main/java/seedu/progresschecker/logic/parser/EditCommandParser.java
  src/main/java/seedu/progresschecker/logic/parser/ParserUtil.java
  src/main/java/seedu/progresschecker/model/ProgressChecker.java
  src/main/java/seedu/progresschecker/model/person/GithubUsername.java
  src/main/java/seedu/progresschecker/model/person/Name.java
  src/main/java/seedu/progresschecker/model/person/Person.java
  src/main/java/seedu/progresschecker/model/util/SampleDataUtil.java
  src/main/java/seedu/progresschecker/storage/XmlAdaptedPerson.java
  src/main/java/seedu/progresschecker/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/XmlProgressCheckerStorageTest/invalidAndValidPersonProgressChecker.xml
  src/test/data/XmlProgressCheckerStorageTest/invalidPersonProgressChecker.xml
  src/test/data/XmlSerializableProgressCheckerTest/invalidPersonProgressChecker.xml
  src/test/data/XmlSerializableProgressCheckerTest/typicalPersonsProgressChecker.xml
  src/test/data/XmlUtilTest/invalidPersonField.xml
  src/test/data/XmlUtilTest/missingPersonField.xml
  src/test/data/XmlUtilTest/tempProgressChecker.xml
  src/test/data/XmlUtilTest/validPerson.xml
  src/test/data/XmlUtilTest/validProgressChecker.xml
  src/test/java/seedu/progresschecker/commons/util/XmlUtilTest.java
  src/test/java/seedu/progresschecker/logic/commands/CommandTestUtil.java
  src/test/java/seedu/progresschecker/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/progresschecker/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/progresschecker/logic/parser/ParserUtilTest.java
  src/test/java/seedu/progresschecker/model/person/GithubUsernameTest.java
  src/test/java/seedu/progresschecker/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/progresschecker/storage/XmlAdaptedPersonTest.java
  src/test/java/seedu/progresschecker/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/progresschecker/testutil/PersonBuilder.java
  src/test/java/seedu/progresschecker/testutil/PersonUtil.java
  src/test/java/seedu/progresschecker/testutil/TypicalPersons.java
  src/test/java/systemtests/AddCommandSystemTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
Labels: type.enhancement

#143 Correct formatting and hyperlinks in User Guide and Developer Guide
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
Labels: type.documentation

#142 Added a create issue task to create github issue from app
  build.gradle
  docs/images/FindCommandUMLDiagram.png
  src/main/java/seedu/progresschecker/logic/CommandFormatListUtil.java
  src/main/java/seedu/progresschecker/logic/commands/AddCommand.java
  src/main/java/seedu/progresschecker/logic/commands/CreateIssue.java
  src/main/java/seedu/progresschecker/logic/commands/DeleteCommand.java
  src/main/java/seedu/progresschecker/logic/commands/FindCommand.java
  src/main/java/seedu/progresschecker/logic/commands/SelectCommand.java
  src/main/java/seedu/progresschecker/logic/commands/ViewCommand.java
  src/main/java/seedu/progresschecker/logic/parser/CliSyntax.java
  src/main/java/seedu/progresschecker/logic/parser/CreateIssueParser.java
  src/main/java/seedu/progresschecker/logic/parser/ParserUtil.java
  src/main/java/seedu/progresschecker/logic/parser/ProgressCheckerParser.java
  src/main/java/seedu/progresschecker/model/Model.java
  src/main/java/seedu/progresschecker/model/ModelManager.java
  src/main/java/seedu/progresschecker/model/ProgressChecker.java
  src/main/java/seedu/progresschecker/model/issues/Assignees.java
  src/main/java/seedu/progresschecker/model/issues/Body.java
  src/main/java/seedu/progresschecker/model/issues/Issue.java
  src/main/java/seedu/progresschecker/model/issues/Labels.java
  src/main/java/seedu/progresschecker/model/issues/Milestone.java
  src/main/java/seedu/progresschecker/model/issues/MilestoneMap.java
  src/main/java/seedu/progresschecker/model/issues/Title.java
  src/test/java/seedu/progresschecker/logic/commands/AddCommandTest.java
Labels: type.epic, type.story, type.task

#141 Upload profile photo from certain path
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  src/main/java/seedu/progresschecker/logic/CommandFormatListUtil.java
  src/main/java/seedu/progresschecker/logic/commands/UploadCommand.java
  src/main/java/seedu/progresschecker/logic/parser/ProgressCheckerParser.java
  src/main/java/seedu/progresschecker/logic/parser/UploadCommandParser.java
  src/main/java/seedu/progresschecker/model/Model.java
  src/main/java/seedu/progresschecker/model/ModelManager.java
  src/main/java/seedu/progresschecker/model/ProgressChecker.java
  src/main/java/seedu/progresschecker/model/person/Person.java
  src/main/java/seedu/progresschecker/ui/PersonCard.java
  src/main/resources/images/contact/user.JPG
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/progresschecker/logic/commands/AddCommandTest.java
  src/test/java/seedu/progresschecker/logic/commands/CommandTestUtil.java
  src/test/java/seedu/progresschecker/logic/commands/UploadCommandTest.java
  src/test/java/seedu/progresschecker/logic/parser/UploadCommandParserTest.java
Labels: type.enhancement

#145 Update ProgressChecker.java
  src/main/java/seedu/progresschecker/model/ProgressChecker.java
Labels: type.bug

#144 first attempt to do UI for tasks
  nulltasklist.html
  src/main/java/seedu/progresschecker/commons/events/ui/LoadTaskEvent.java
  src/main/java/seedu/progresschecker/logic/CommandFormatListUtil.java
  src/main/java/seedu/progresschecker/logic/apisetup/ConnectTasksApi.java
  src/main/java/seedu/progresschecker/logic/commands/ViewTaskListCommand.java
  src/main/java/seedu/progresschecker/logic/parser/ParserUtil.java
  src/main/java/seedu/progresschecker/logic/parser/ProgressCheckerParser.java
  src/main/java/seedu/progresschecker/logic/parser/ViewTaskListCommandParser.java
  src/main/java/seedu/progresschecker/model/issues/Issue.java
  src/main/java/seedu/progresschecker/model/task/MyTaskList.java
  src/main/java/seedu/progresschecker/ui/BrowserPanel.java
  src/main/resources/view/TaskDetailsPanel.fxml
  src/main/resources/view/TaskListCard.fxml
  src/main/resources/view/TaskListPanel.fxml
  src/main/resources/view/sampleTasklist.html
  src/main/resources/view/tasklist.html
Labels: type.enhancement

#146 Task management bugfix1
  src/main/java/seedu/progresschecker/commons/events/ui/LoadTaskEvent.java
  src/main/java/seedu/progresschecker/logic/apisetup/ConnectTasksApi.java
  src/main/java/seedu/progresschecker/logic/commands/ViewTaskListCommand.java
  src/main/java/seedu/progresschecker/ui/BrowserPanel.java
  src/main/resources/client_id.json
Labels: type.bug fix
